config:
  local-cloud-pulumi:environment: dev
  aws:endpoints:
    - s3: http://localhost:4566
      ec2: http://localhost:4566
      iam: http://localhost:4566
      sts: http://localhost:4566
      ecs: http://localhost:4566
      dynamodb: http://localhost:4566
      ecr: http://localhost:4566